var propuestas = null
//propuestas (titulo, propuesta, ramas, idCandidato, idPArtido)
function CargarPropuestas()
{
propuestas = [

//Ignacio peralta
Propuesta("Empleo", " El “Programa manos a la obra” es una estrategia de compromisos y acciones para obtener empleos, una de las grandes demandas de los colimenses. Impulsaremos una serie de acciones  que permitirán atraer inversiones y generar opciones de trabajo, para que la población tenga una oportunidad de superación a través de un empleo digno y bien remunerado, también existe la necesidad que la gente que ya tiene empleo tenga un mejor salario y corresponda a su nivel de preparación, experiencia, habilidad y empeño.", temas.PLANEAMIENTO_URBANO, 0, 0),
Propuesta("Seguridad", " Los colimenses anhelamos recuperar el Colima del cual nos sentíamos profundamente orgullosos por ser el estado más seguro del país. Con el “Programa seguridad integral”, lo lograremos. Este programa jugará un papel fundamental en la estrategia de gobierno, así como en la definición de acciones y políticas públicas. Invertiremos en los cuerpos policiacos, para equiparlos y entrenarlos mejor, además de una serie de medidas para dar la certeza que lograremos este objetivo.", temas.SEGURIDAD, 0, 0),
Propuesta("Combate a la probreza", "Muchos colimenses no han tenido la oportunidad para mejorar su calidad de vida y aún los aquejan carencias importantes, como la falta de alimento, vivienda o servicios; definiremos acciones para generar las condiciones que eliminen dicha problemática, a través de becas, programas sociales y ayuda alimentaria.", temas.ECONOMIA, 0, 0),
Propuesta("Infraestructura", "Es sumamente necesario contar con más y mejor infraestructura de todo tipo. De comunicación, transporte, recreativa y productiva, que permita impulsar el desarrollo económico de Colima, así como la atracción de inversiones que conlleven a la generación de empleos. Con el “Programa infraestructura para el desarrollo”, gestionaremos incrementar, ampliar y mejorar las carreteras, impulsaremos el desarrollo portuario para que Manzanillo siga siendo el motor del crecimiento económico y se traduzca en efectos positivos en la calidad de vida de los colimenses.", temas.TRANSPORTE, 0, 0),
Propuesta("Campo", " Los campesinos, agricultores y productores colimenses pasan por problemas relacionados a plagas, financiamiento para la producción y comercialización. Propondré una serie de acciones que permitirán remediar dicha situación y apoyar a los trabajadores a recuperar y sanar su principal fuente de ingresos. Buscando, por todos los medios, poner a su disposición las herramientas necesarias para dar un mayor valor agregado a sus productos, así como acceso a nuevos mercados.", temas.ECONOMIA, 0, 0),
Propuesta("Educación", "Aseguraremos que exista una formación de calidad con el “Programa educación para todos”, para ello apoyaremos al magisterio, de manera que puedan brindar un servicio óptimo a jóvenes y niños colimenses. Mientras tengamos mejores planes de estudio, vamos a tener la posibilidad de que Colima pueda volver a ser un estado en crecimiento y con mayor competitividad a nivel nacional e internacional.", temas.EDUCACION, 0, 0),
Propuesta("Turismo", "El sector turístico representa la generación de empleos e ingresos para un gran sector de la sociedad colimense, el cual no ha liberado su máximo potencial. Impulsaremos de manera decidida a dicho sector  como una estrategia fundamental para el desarrollo económico de la entidad.", temas.ECONOMIA, 0, 0),
Propuesta("Salud", "Me queda claro que de nada sirve tener infraestructura, educación y seguridad si no se tiene una vida saludable, por esa razón priorizaremos el abasto seguro de medicamentos y la mejora continua del sector salud, así como la existencia de personal médico que brinde servicios rápidos y de calidad, evitando las horas de espera por parte de los pacientes para ser atendidos, así como un trato digno a los mismos.", temas.SALUD, 0, 0),

// Jorge Luis preciado
Propuesta("Rescatar a colima de la inseguridad", "De 100 delitos, 96 nunca se denuncian por la pasividad e ineficiencia en los Ministerios Públicos, por lo que se creará una policía con rostro humano. Haremos un frente común para combatir la drogadicción, y así reconstruir el tejido social.", temas.SEGURIDAD, 1, 0 ),
Propuesta("Mejor preparación de policias", "La Policía de Colima será reconocida en todo México por su preparación, adiestramiento, equipamiento y por defender y respetar siempre los Derechos Humanos de todas las personas, sin importar su origen, condición social o económica.", temas.SEGURIDAD, 1, 0 ),
Propuesta("Sistema de Respuesta inmediata", "Brindaremos atención pronta y oportuna a las llamadas de auxilio, denuncias y crisis en cuestión de segundos, aprovechando correctamente los avances tecnológicos, la geolocalización, mapas delincuenciales e inteligencia policíaca. Nunca más, un colimense recibirá auxilio de manera tardía", temas.SEGURIDAD, 1, 0 ),
Propuesta("Sin desudas", "Resolveremos la crisis financiera del gobierno estatal y de los gobiernos municipales, además de darle viabilidad a esta propuesta de desarrollo.", temas.ECONOMIA, 1, 0 ),
Propuesta("Más y mejores ingresos", "Habrá orden, transparencia, eficiencia y control en el gasto, pero también una nueva e importante fuente de ingresos para el estado, a través de la riqueza que genera para el fisco federal el puerto de Manzanillo.", temas.ECONOMIA, 1, 0 ),
Propuesta("Transparencia", "Habrá una revisión exhaustiva en el gasto del gobierno estatal desde 1997 a la fecha, pues el pueblo de Colima tiene todo el derecho de conocer la verdad, sólo así habrá justicia, los habitantes de Colima deben conocer la verdad, a dónde fueron a parar esos 4 mil 800 millones de pesos de los que nadie ha dado cuentas.", temas.ECONOMIA, 1, 0 ),
Propuesta("Justicia", "En Colima no ha habido casos de funcionarios que hayan ido a la cárcel por corruptos, y no porque no los haya, sino porque se les ha dejado escapar, por eso necesitamos que se les persiga a esos delincuentes, para destituirlos y hacerles que regresen los recursos a los ciudadanos.", temas.SOCIEDAD, 1, 0 ),
Propuesta("Fortalecimiento de la justicia", "Instauraremos en Colima el Sistema Estatal Anticorrupción, sostenido en cuatro pilares: la Auditoría Superior, la Contraloría del Estado, una Fiscalía Especializada en la materia y un Consejo Ciudadano de ética pública. Con este sistema, todos estaremos atentos y al tanto del manejo, de la aplicación correcta de los recursos que son de los colimenses.", temas.SOCIEDAD, 1, 0 ),
Propuesta("Más oportunidad a familias colimenses", "En mi gobierno ningún familiar ocupará la titularidad de organismos tan importantes como lo es el DIF. Le devolveremos el sentido para el cual fue creado: apoyar el desarrollo de las familias colimenses y no de las familias de los gobernantes", temas.SOCIEDAD, 1, 0 ),
Propuesta("Más transparencia", "Terminaremos con la opacidad y discrecionalidad con la que se han manejado los recursos derivados del impuesto al 2 por ciento sobre nómina, el Sefidec; a través de un comité cuyas sesiones serán transmitidas vía internet, revisaremos que esos recursos se inviertan correctamente.", temas.ECONOMIA, 1, 0 ),
Propuesta("Apoyemos al turismo", "En el sector turistico en Colima hace falta un mayor aprovechamiento en tres zonas: la volcánica, la de balnearios y la de playas, para lo cual, gestionará obras a fin de impulsar a este sector. Emprenderemos el programa de promoción turística más importante que se haya realizado para difundir las bellezas naturales de Colima y los servicios que ofrecen nuestras tres zonas turísticas, así como el mega proyecto Nuevo Manzanillo, que será un relanzamiento de los sitios que colindan con este importante destino.", temas.ECONOMIA, 1, 0 ),
Propuesta("Queremos puros alumnos de 10", "Se apoyará a los estudiantes para que solamente se preocupen por estudiar, para buscar incrementar el rendimiento de todos los jovenes.", temas.EDUCACION, 1, 0 ),
Propuesta("Bajo el mismo techo", "Implementaremos el programa Bajo el mismo techo, el cual con gestiones ante la Federación será el programa de vivienda más importante en la historia de Colima, que se enfocará en ayudar a más de 30 mil familias de la entidad.", temas.VIVIENDA, 1, 0 ),
Propuesta("Buen uso de recursos", "El uso urbano del agua, la explotación minera en los ejidos y el número cada vez mayor de automotores son temas que nos preocupan y ocupan. Por lo cual el futuro deseable es llegar a la cero emisión de contaminantes en nuestro espacio, nuestro gobierno pondrá la primera piedra instrumentando políticas públicas y programas encaminados a que nuestras generaciones futuras alcancen a disfrutar de una nueva realidad en materia ecológica", temas.MEDIO_AMBIENTE, 1, 0 ),
Propuesta("Equidad de genero", "Hoy es una realidad gracias a la reforma política que las mujeres aspiren en igualdad de número a todos los cargos de elección popular, ahora falta llevar ese espíritu a los demás ámbitos de los sectores público y privado para que la mujer se inserte en igualdad de condiciones y, sobre todo, de número a la actividad de nuestra organización social.", temas.ECONOMIA, 1, 0 ),
Propuesta("Un compromiso con los 10 municipios", "En Armería, poner en funcionamiento el hospital regional; en Comala, cuidar el medio ambiente; en Colima, sacar vías del tren de la ciudad; en Coquimatlán, construir un gran polideportivo; en Cuauhtémoc, remodelar del centro histórico y mejorar la fisonomía de Quesería, En Manzanillo ampliar libramiento a cuatro carriles hasta la comunidad de El Naranjo; en Minatitlán, construir muro en el cerro Los Copales; en Ixtlahuacán, construir el hospital; en Tecomán, evitar inundaciones, y en Villa de Álvarez, gestionar un auditorio para 12 mil personas", temas.PLANEAMIENTO_URBANO, 1, 0 ),

//Martha Maria Zepeda 
Propuesta("Educación", "Garantizar alimentación, educación gratuita desde preescolar hasta nivel profesional",  temas.EDUCACION, 2, 0),
Propuesta("Salud", "Mejorar los servicios de salud y abastecimiento de medicinas",  temas.SALUD, 2, 0),
Propuesta("Derechos Humanos", "Procurar los derechos humanos de las personas",  temas.DERECHOS_HUMANOS, 2, 0),
Propuesta("Inversión", "Promover la inversión, detonar con eficiencia al sector turístico",  temas.ECONOMIA, 2, 0),
Propuesta("Seguridad", "Volver a Colima una entidad segura y reducir la deuda pública.",  temas.SEGURIDAD, 2, 0),

//José Francisco Gallardo
Propuesta("Seguridad", "Busco el respeto de las autonomías comunitarias, la cuales son la base para restablecer la seguridad. No se trata de tener más policías o cárceles sino de hacer una sociedad organizada con base al respeto a los derechos humanos",  temas.SEGURIDAD, 4, 0),

//Carlos Barbazán 
Propuesta("Todos juntos", "Lograré una sinergia con las diferentes instituciones médicas como el IMSS, ISSSTE, Seguro Popular, con el objetivo de que se atienda cualquier emergencia de la población sin importar la institución", temas.SALUD, 5, 0),
Propuesta("Igualdad", "Para las personas con capacidades diferentes se requiere tener una conexión con fundaciones con el fin de gestionar aparatos para que puedan mejorar su calidad de vida", temas.DERECHOS_HUMANOS, 5, 0),
Propuesta("Empleos", "Atraeré fuentes empleo con maquiladoras gracias a la instalación de dos empresas armadoras de vehículos a partir de julio en Colima, que brindarán 10 mil empleos.", temas.ECONOMIA, 5, 0),
Propuesta("Mayor seguridad", "Los policías tendrán mayor capacidad y habrá más elementos porque en la actualidad son insuficientes. Crearé escuelas de policías donde los agentes sean colimenses con la vocación de servir", temas.SEGURIDAD, 5, 0),
Propuesta("Educación gratuita", "La educación debe ser gratuita y de tiempo completo, desde guarderías hasta primarias, donde deberán contemplar médicos que resguarden la integridad de los estudiantes.", temas.EDUCACION, 5, 0),
Propuesta("Deporte y cultura", "Con esta propuesta se busca alejar a los jóvenes de otro tipo de situaciones que ponen en riesgo su vida como las adicciones", temas.PLANEAMIENTO_URBANO, 5, 0),


// Gerardo Galván
Propuesta("Adiós financiamientos", "Ecabar con los financiamientos a los partidos políticos y que las campañas le cuestenpor igual a todos los involucrados, de tal forma que los recursos públicos sean usados en beneficio de la gente.", temas.ECONOMIA, 6, 0),
Propuesta("Mejorar seguridad, educación ysalud", "Se logrará con una actitud más responsable de parte de los funcionarios, generar una conciencia con valores que permitan que haya mejores policías, mejor trato o atención a la población, así como atender las necesidades de obra o de ayuda a los estudiantes.", temas.PLANEAMIENTO_URBANO, 6, 0),

// Leoncio Alfonso Morán
Propuesta("El primer eje", "Implementar un correcto uso de los recursos, transparencia y rendición de cuentas.", temas.ECONOMIA, 7, 0),
Propuesta("El segundo eje", "Recuperar la tranquilidad en los espacios públicos y políticas de prevención del delito.", temas.SEGURIDAD, 7, 0),
Propuesta("El tercer eje", "Revocación del mandato, dado que a los 3 años hará una audiencia para poder revocar su mandato si no hace un buen gobierno.", temas.SOCIEDAD, 7, 0),
Propuesta("El cuarto eje", "Cambiar la historia con educación y cultura; útiles y uniformes escolares gratuitos; comedores, infraestructura para eventos de cultura y becas para estudiantes.", temas.EDUCACION, 7, 0),
Propuesta("El quinto eje", "Ofrecer oportunidades y apoyos para grupos vulnerables.", temas.ECONOMIA, 7, 0),
Propuesta("El sexto eje", "Dar un servicio de salud de calidad a los colimenses.", temas.SALUD, 7, 0),
Propuesta("El septimo eje", "Ofrecer un desarrollo económico sustentable para el mantenimiento y creación Pymes, incentivando la creación de empleos formales al derogar el impuesto del 2 por ciento a la nómina.", temas.ECONOMIA, 7, 0),
Propuesta("El octavo eje", "Trata de invertir en la obra pública donde más se necesita.", temas.ECONOMIA, 7, 0)


];
}
